import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import { library } from "@fortawesome/fontawesome-svg-core";
import { fab } from "@fortawesome/free-brands-svg-icons";
import { fas } from "@fortawesome/free-solid-svg-icons";
import { far } from "@fortawesome/free-regular-svg-icons";

import { cookies } from "next/headers";
import { authOptions } from "~/server/auth";
import { Providers } from "./_components/providers";
import { getServerSession } from "next-auth";

library.add(fab, fas, far);

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "RH Devs",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/rhdevs.png" }],
};

const serverSession = await getServerSession(authOptions);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`font-sans ${inter.variable}`}>
        <Providers serverSession={serverSession}>
          <TRPCReactProvider cookies={cookies().toString()}>
            {children}
          </TRPCReactProvider>
        </Providers>
      </body>
    </html>
  );
}
